# Generated by Django 3.2 on 2021-04-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokerapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="friend_group",
        ),
        migrations.RemoveField(
            model_name="player",
            name="friends",
        ),
        migrations.RemoveField(
            model_name="player",
            name="user",
        ),
        migrations.AddField(
            model_name="game",
            name="big_blind",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="games_current_player",
                to="pokerapi.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="pot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="small_blind",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="money",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(default="x", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="pot_money",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games_played", to="pokerapi.Player"
            ),
        ),
        migrations.DeleteModel(
            name="FriendGroup",
        ),
    ]
