# Generated by Django 3.2 on 2021-04-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapi', '0002_auto_20210410_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
