# Generated by Django 3.2 on 2021-04-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerapi', '0003_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
