# Generated by Django 3.2 on 2021-04-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokerapi", "0006_alter_game_current_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="starting_money",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[("ONLINE", "ONLINE"), ("BREAK", "BREAK"), ("LEFT", "LEFT")],
                default="ONLINE",
                max_length=10,
            ),
        ),
    ]
